package service

const (
	ERROR_CODE_MSG_HISTORY_PROTOCOL_UNMARSHAL_ERR int32 = 5001
	ERROR_CODE_MSG_HISTORY_PROTOCOL_MARSHAL_ERR   int32 = 5002
	ERROR_CODE_MSG_HISTORY_GRPC_SERVICE_FAILURE   int32 = 5003
	ERROR_CODE_MSG_HISTORY_MSG_PUSH_FAILED        int32 = 5004
	ERROR_CODE_MSG_HISTORY_MSG_ENQUEUE_FAILED     int32 = 5005
	ERROR_CODE_MSG_HISTORY_GET_SEQ_ID_FAILED      int32 = 5006
	ERROR_CODE_MSG_HISTORY_INSERT_MESSAGE_FAILED  int32 = 5007
	ERROR_CODE_MSG_HISTORY_CHCHE_MESSAGE_FAILED   int32 = 5008
	ERROR_CODE_MSG_HISTORY_UPDATE_VALUE_FAILED    int32 = 5009
	ERROR_CODE_MSG_HISTORY_QUERY_DB_FAILED        int32 = 5010
	ERROR_CODE_MSG_HISTORY_REDIS_GET_FAILED       int32 = 5011
)

const (
	ERROR_MSG_HISTORY_PROTOCOL_UNMARSHAL_ERR = "协议反序列化错误"
	ERROR_MSG_HISTORY_PROTOCOL_MARSHAL_ERR   = "协议序列化错误"
	ERROR_MSG_HISTORY_GRPC_SERVICE_FAILURE   = "服务故障"
	ERROR_MSG_HISTORY_MSG_PUSH_FAILED        = "消息推送失败"
	ERROR_MSG_HISTORY_MSG_ENQUEUE_FAILED     = "消息ENQUEUE失败"
	ERROR_MSG_HISTORY_GET_SEQ_ID_FAILED      = "生成 SEQUENCE ID 失败"
	ERROR_MSG_HISTORY_INSERT_MESSAGE_FAILED  = "消息入库失败"
	ERROR_MSG_HISTORY_CHCHE_MESSAGE_FAILED   = "消息缓存失败"
	ERROR_MSG_HISTORY_UPDATE_VALUE_FAILED    = "更新Value失败"
	ERROR_MSG_HISTORY_QUERY_DB_FAILED        = "查询失败"
	ERROR_MSG_HISTORY_REDIS_GET_FAILED       = "读取 redis 缓存失败"
)
