package service

import (
	"errors"
)

const (
	ERROR_CODE_MESSAGE_UNMARSHAL_ERR               int32 = 4001
	ERROR_CODE_MESSAGE_VALIDATOR_ERR               int32 = 4002
	ERROR_CODE_MESSAGE_REPEATED_MESSAGE            int32 = 4003
	ERROR_CODE_MESSAGE_ENQUEUE_FAILED              int32 = 4004
	ERROR_CODE_MESSAGE_RECORD_MSGID_FAILED         int32 = 4005
	ERROR_CODE_MESSAGE_INCR_SEQ_ID_FAILED          int32 = 4006
	ERROR_CODE_MESSAGE_DECR_SEQ_ID_FAILED          int32 = 4007
	ERROR_CODE_MESSAGE_VERIFY_IDENTITY_FAILED      int32 = 4008
	ERROR_CODE_MESSAGE_REDIS_GET_FAILED            int32 = 4009
	ERROR_CODE_MESSAGE_GRPC_SERVICE_FAILURE        int32 = 4010 // 服务故障
	ERROR_CODE_MESSAGE_CHCHE_MESSAGE_FAILED        int32 = 4011
	ERROR_CODE_MESSAGE_UPDATE_CHCHE_MESSAGE_FAILED int32 = 4012
	ERROR_CODE_MESSAGE_BEYOND_OPERABLE_TIME        int32 = 4013
	ERROR_CODE_MESSAGE_GET_SENDER_INFO_FAILED      int32 = 4014
	ERROR_CODE_MESSAGE_PRODUCER_IS_NULL            int32 = 4015
	ERROR_CODE_MESSAGE_GRPC_LINK_TIMEOUT           int32 = 4016
)

const (
	ERROR_MESSAGE_UNMARSHAL_ERR               = "消息反序列化错误"
	ERROR_MESSAGE_VALIDATOR_ERR               = "参数校验错误"
	ERROR_MESSAGE_REPEATED_MESSAGE            = "重复的消息"
	ERROR_MESSAGE_ENQUEUE_FAILED              = "消息入队失败"
	ERROR_MESSAGE_RECORD_MSGID_FAILED         = "缓存消息ID失败"
	ERROR_MESSAGE_INCR_SEQ_ID_FAILED          = "生成 Sequence ID 失败"
	ERROR_MESSAGE_DECR_SEQ_ID_FAILED          = "更新 Sequence ID 失败"
	ERROR_MESSAGE_VERIFY_IDENTITY_FAILED      = "验证身份失败"
	ERROR_MESSAGE_REDIS_GET_FAILED            = "读取redis缓存失败"
	ERROR_MESSAGE_GRPC_SERVICE_FAILURE        = "服务故障"
	ERROR_MESSAGE_CHCHE_MESSAGE_FAILED        = "消息缓存失败"
	ERROR_MESSAGE_UPDATE_CHCHE_MESSAGE_FAILED = "更新缓存消息失败"
	ERROR_MESSAGE_BEYOND_OPERABLE_TIME        = "仅可撤回 10 minutes 内的消息"
	ERROR_MESSAGE_GET_SENDER_INFO_FAILED      = "获取发送者信息失败"
	ERROR_MESSAGE_PRODUCER_IS_NULL            = "消息生成者为null"
	ERROR_MESSAGE_GRPC_LINK_TIMEOUT           = "GRPC 服务超时"
)

var (
	ERROR_MESSAGE_BODY_TEXT_EMPTY_ERR = errors.New("消息为空")
	ERROR_MESSAGE_OUT_MAX_RANGE       = errors.New("消息超出规定长度")
	ERROR_MESSAGE_NON_CONTACT_ERR     = errors.New("非联系人")
	ERROR_MESSAGE_NON_CHAT_MEMBER_ERR = errors.New("非联 Chat 成员")
)

const (
	MAX_MESSAGE_LENGTH = 1500
)
