// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.28.1
// source: pb_msg/msg.proto

package pb_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb_chat "lark/pkg/proto/pb_chat"
	pb_chat_member "lark/pkg/proto/pb_chat_member"
	pb_enum "lark/pkg/proto/pb_enum"
	pb_invite "lark/pkg/proto/pb_invite"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic    pb_enum.TOPIC        `protobuf:"varint,1,opt,name=topic,proto3,enum=pb_enum.TOPIC" json:"topic,omitempty"`
	SubTopic pb_enum.SUB_TOPIC    `protobuf:"varint,2,opt,name=sub_topic,json=subTopic,proto3,enum=pb_enum.SUB_TOPIC" json:"sub_topic,omitempty"`
	MsgType  pb_enum.MESSAGE_TYPE `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3,enum=pb_enum.MESSAGE_TYPE" json:"msg_type,omitempty"` // 消消息类型(srv消息才有)
	MsgId    int64                `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                 // 消息ID(cli消息才有)
	Data     []byte               `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetTopic() pb_enum.TOPIC {
	if x != nil {
		return x.Topic
	}
	return pb_enum.TOPIC(0)
}

func (x *Packet) GetSubTopic() pb_enum.SUB_TOPIC {
	if x != nil {
		return x.SubTopic
	}
	return pb_enum.SUB_TOPIC(0)
}

func (x *Packet) GetMsgType() pb_enum.MESSAGE_TYPE {
	if x != nil {
		return x.MsgType
	}
	return pb_enum.MESSAGE_TYPE(0)
}

func (x *Packet) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MsgId int64  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 消息ID
	IsSrv bool   `protobuf:"varint,4,opt,name=is_srv,json=isSrv,proto3" json:"is_srv,omitempty"` // true:sender_id false:cli_msg_id
}

func (x *MessageResp) Reset() {
	*x = MessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResp) ProtoMessage() {}

func (x *MessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResp.ProtoReflect.Descriptor instead.
func (*MessageResp) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MessageResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MessageResp) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageResp) GetIsSrv() bool {
	if x != nil {
		return x.IsSrv
	}
	return false
}

type CliChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,gt=0"
	CliMsgId int64 `protobuf:"varint,1,opt,name=cli_msg_id,json=cliMsgId,proto3" json:"cli_msg_id,omitempty" validate:"required,gt=0"` // 客户端消息号
	// @inject_tag: validate:"required,gt=0"
	SenderId int64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty" validate:"required,gt=0"` // 发送者uid 【无需传】
	// @inject_tag: validate:"required,gte=0"
	SenderPlatform pb_enum.PLATFORM_TYPE `protobuf:"varint,3,opt,name=sender_platform,json=senderPlatform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"sender_platform,omitempty" validate:"required,gte=0"` // 发送者平台 【无需传】
	// @inject_tag: validate:"required,gt=0"
	ChatId int64 `protobuf:"varint,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty" validate:"required,gt=0"` // 会话ID
	// @inject_tag: validate:"required,gt=0"
	MsgType pb_enum.MSG_TYPE `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3,enum=pb_enum.MSG_TYPE" json:"msg_type,omitempty" validate:"required,gt=0"` // 消息类型
	Body    []byte           `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`                                             // 消息本体
	// @inject_tag: validate:"required,gt=0"
	SentTs int64 `protobuf:"varint,7,opt,name=sent_ts,json=sentTs,proto3" json:"sent_ts,omitempty" validate:"required,gt=0"` // 客户端本地发送时间
}

func (x *CliChatMessage) Reset() {
	*x = CliChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CliChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliChatMessage) ProtoMessage() {}

func (x *CliChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliChatMessage.ProtoReflect.Descriptor instead.
func (*CliChatMessage) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *CliChatMessage) GetCliMsgId() int64 {
	if x != nil {
		return x.CliMsgId
	}
	return 0
}

func (x *CliChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CliChatMessage) GetSenderPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.SenderPlatform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

func (x *CliChatMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *CliChatMessage) GetMsgType() pb_enum.MSG_TYPE {
	if x != nil {
		return x.MsgType
	}
	return pb_enum.MSG_TYPE(0)
}

func (x *CliChatMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CliChatMessage) GetSentTs() int64 {
	if x != nil {
		return x.SentTs
	}
	return 0
}

type SrvChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrvMsgId       int64                 `protobuf:"varint,1,opt,name=srv_msg_id,json=srvMsgId,proto3" json:"srv_msg_id,omitempty"`                                            // 服务端消息号
	CliMsgId       int64                 `protobuf:"varint,2,opt,name=cli_msg_id,json=cliMsgId,proto3" json:"cli_msg_id,omitempty"`                                            // 客户端消息号
	SenderId       int64                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                                              // 发送者uid
	SenderPlatform pb_enum.PLATFORM_TYPE `protobuf:"varint,4,opt,name=sender_platform,json=senderPlatform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"sender_platform,omitempty"` // 发送者平台
	SenderName     string                `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`                                         // 发送者姓名
	SenderAvatar   string                `protobuf:"bytes,6,opt,name=sender_avatar,json=senderAvatar,proto3" json:"sender_avatar,omitempty"`                                   // 发送者头像
	ChatId         int64                 `protobuf:"varint,7,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`                                                    // 会话ID
	ChatType       pb_enum.CHAT_TYPE     `protobuf:"varint,8,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"`                       // 会话类型
	SeqId          int64                 `protobuf:"varint,9,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                                                       // 消息唯一ID
	MsgFrom        pb_enum.MSG_FROM      `protobuf:"varint,10,opt,name=msg_from,json=msgFrom,proto3,enum=pb_enum.MSG_FROM" json:"msg_from,omitempty"`                          // 消息来源
	MsgType        pb_enum.MSG_TYPE      `protobuf:"varint,11,opt,name=msg_type,json=msgType,proto3,enum=pb_enum.MSG_TYPE" json:"msg_type,omitempty"`                          // 消息类型
	Body           []byte                `protobuf:"bytes,12,opt,name=body,proto3" json:"body,omitempty"`                                                                      // 消息本体
	Status         int32                 `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`                                                                 // 消息状态
	SentTs         int64                 `protobuf:"varint,14,opt,name=sent_ts,json=sentTs,proto3" json:"sent_ts,omitempty"`                                                   // 客户端本地发送时间
	SrvTs          int64                 `protobuf:"varint,15,opt,name=srv_ts,json=srvTs,proto3" json:"srv_ts,omitempty"`                                                      // 服务端接收消息的时间
	AssocId        int64                 `protobuf:"varint,16,opt,name=assoc_id,json=assocId,proto3" json:"assoc_id,omitempty"`                                                // 关联ID
}

func (x *SrvChatMessage) Reset() {
	*x = SrvChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrvChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrvChatMessage) ProtoMessage() {}

func (x *SrvChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrvChatMessage.ProtoReflect.Descriptor instead.
func (*SrvChatMessage) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SrvChatMessage) GetSrvMsgId() int64 {
	if x != nil {
		return x.SrvMsgId
	}
	return 0
}

func (x *SrvChatMessage) GetCliMsgId() int64 {
	if x != nil {
		return x.CliMsgId
	}
	return 0
}

func (x *SrvChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SrvChatMessage) GetSenderPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.SenderPlatform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

func (x *SrvChatMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SrvChatMessage) GetSenderAvatar() string {
	if x != nil {
		return x.SenderAvatar
	}
	return ""
}

func (x *SrvChatMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SrvChatMessage) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *SrvChatMessage) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *SrvChatMessage) GetMsgFrom() pb_enum.MSG_FROM {
	if x != nil {
		return x.MsgFrom
	}
	return pb_enum.MSG_FROM(0)
}

func (x *SrvChatMessage) GetMsgType() pb_enum.MSG_TYPE {
	if x != nil {
		return x.MsgType
	}
	return pb_enum.MSG_TYPE(0)
}

func (x *SrvChatMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SrvChatMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SrvChatMessage) GetSentTs() int64 {
	if x != nil {
		return x.SentTs
	}
	return 0
}

func (x *SrvChatMessage) GetSrvTs() int64 {
	if x != nil {
		return x.SrvTs
	}
	return 0
}

func (x *SrvChatMessage) GetAssocId() int64 {
	if x != nil {
		return x.AssocId
	}
	return 0
}

type ReadReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                     // 用户ID
	ChatId int64 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"` // 会话ID
	SeqId  int64 `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`    // 消息唯一ID
}

func (x *ReadReceipt) Reset() {
	*x = ReadReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceipt) ProtoMessage() {}

func (x *ReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceipt.ProtoReflect.Descriptor instead.
func (*ReadReceipt) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *ReadReceipt) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReadReceipt) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ReadReceipt) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type ChatSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId   int64            `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`                           // 会话ID
	SeqId    int64            `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                              // 消息唯一ID
	SrvTs    int64            `protobuf:"varint,3,opt,name=srv_ts,json=srvTs,proto3" json:"srv_ts,omitempty"`                              // 服务端接收消息的时间
	SenderId int64            `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                     // 发送者uid
	MsgFrom  pb_enum.MSG_FROM `protobuf:"varint,10,opt,name=msg_from,json=msgFrom,proto3,enum=pb_enum.MSG_FROM" json:"msg_from,omitempty"` // 消息来源
}

func (x *ChatSeq) Reset() {
	*x = ChatSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSeq) ProtoMessage() {}

func (x *ChatSeq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSeq.ProtoReflect.Descriptor instead.
func (*ChatSeq) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *ChatSeq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatSeq) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *ChatSeq) GetSrvTs() int64 {
	if x != nil {
		return x.SrvTs
	}
	return 0
}

func (x *ChatSeq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatSeq) GetMsgFrom() pb_enum.MSG_FROM {
	if x != nil {
		return x.MsgFrom
	}
	return pb_enum.MSG_FROM(0)
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,min=32,max=50"
	ImageKey string `protobuf:"bytes,1,opt,name=image_key,json=imageKey,proto3" json:"image_key,omitempty" validate:"required,min=32,max=50"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *Image) GetImageKey() string {
	if x != nil {
		return x.ImageKey
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,min=32,max=50"
	FileKey string `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty" validate:"required,min=32,max=50"`
	// @inject_tag: validate:"required"
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty" validate:"required"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{7}
}

func (x *File) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *File) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type Audio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,min=32,max=50"
	FileKey string `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty" validate:"required,min=32,max=50"`
	// @inject_tag: validate:"gt=500"
	Duration int32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty" validate:"gt=500"`
}

func (x *Audio) Reset() {
	*x = Audio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{8}
}

func (x *Audio) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *Audio) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,min=32,max=50"
	FileKey string `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty" validate:"required,min=32,max=50"`
	// @inject_tag: validate:"required,min=32,max=50"
	ImageKey string `protobuf:"bytes,2,opt,name=image_key,json=imageKey,proto3" json:"image_key,omitempty" validate:"required,min=32,max=50"`
	// @inject_tag: validate:"required"
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty" validate:"required"`
	// @inject_tag: validate:"gt=500"
	Duration int32 `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty" validate:"gt=500"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{9}
}

func (x *Media) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *Media) GetImageKey() string {
	if x != nil {
		return x.ImageKey
	}
	return ""
}

func (x *Media) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Media) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type GiveRedEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,gt=0"
	EnvId int64 `protobuf:"varint,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty" validate:"required,gt=0"` // 红包ID
	// @inject_tag: validate:"required,gt=0"
	EnvType pb_enum.RED_ENVELOPE_TYPE `protobuf:"varint,2,opt,name=env_type,json=envType,proto3,enum=pb_enum.RED_ENVELOPE_TYPE" json:"env_type,omitempty" validate:"required,gt=0"` // 红包类型 1-均分红包 2-碰运气红包
	// @inject_tag: validate:"required,gt=0"
	ReceiverType pb_enum.RECEIVER_TYPE `protobuf:"varint,3,opt,name=receiver_type,json=receiverType,proto3,enum=pb_enum.RECEIVER_TYPE" json:"receiver_type,omitempty" validate:"required,gt=0"` // 接收者类型 1-私聊对方 2-群聊所有人 3-群聊指定人
	// @inject_tag: validate:"required"
	TradeNo string `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty" validate:"required"` // 交易编号
	// @inject_tag: validate:"required,gt=0"
	SenderUid int64 `protobuf:"varint,5,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty" validate:"required,gt=0"` // 发红包用户ID
	// @inject_tag: validate:"required,gt=0"
	Total int64 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty" validate:"required,gt=0"` // 红包总金额(分)
	// @inject_tag: validate:"required,gt=0"
	Quantity int32 `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty" validate:"required,gt=0"` // 红包数量
	// @inject_tag: validate:"required"
	Message      string  `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty" validate:"required"`                                       // 祝福语
	ReceiverUids []int64 `protobuf:"varint,9,rep,packed,name=receiver_uids,json=receiverUids,proto3" json:"receiver_uids,omitempty"` // 接收者ID
	// @inject_tag: validate:"required,gt=0"
	ExpiredTs int64 `protobuf:"varint,10,opt,name=expired_ts,json=expiredTs,proto3" json:"expired_ts,omitempty" validate:"required,gt=0"` // 红包过期时间
}

func (x *GiveRedEnvelope) Reset() {
	*x = GiveRedEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveRedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRedEnvelope) ProtoMessage() {}

func (x *GiveRedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRedEnvelope.ProtoReflect.Descriptor instead.
func (*GiveRedEnvelope) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{10}
}

func (x *GiveRedEnvelope) GetEnvId() int64 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *GiveRedEnvelope) GetEnvType() pb_enum.RED_ENVELOPE_TYPE {
	if x != nil {
		return x.EnvType
	}
	return pb_enum.RED_ENVELOPE_TYPE(0)
}

func (x *GiveRedEnvelope) GetReceiverType() pb_enum.RECEIVER_TYPE {
	if x != nil {
		return x.ReceiverType
	}
	return pb_enum.RECEIVER_TYPE(0)
}

func (x *GiveRedEnvelope) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *GiveRedEnvelope) GetSenderUid() int64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *GiveRedEnvelope) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GiveRedEnvelope) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GiveRedEnvelope) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GiveRedEnvelope) GetReceiverUids() []int64 {
	if x != nil {
		return x.ReceiverUids
	}
	return nil
}

func (x *GiveRedEnvelope) GetExpiredTs() int64 {
	if x != nil {
		return x.ExpiredTs
	}
	return 0
}

type ReceiveRedEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,gt=0"
	EnvId int64 `protobuf:"varint,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty" validate:"required,gt=0"` // 红包ID
	// @inject_tag: validate:"required,gt=0"
	ReceiverUid int64 `protobuf:"varint,2,opt,name=receiver_uid,json=receiverUid,proto3" json:"receiver_uid,omitempty" validate:"required,gt=0"` // 领取人UID
	// @inject_tag: validate:"required"
	ReceiverNickname string `protobuf:"bytes,3,opt,name=receiver_nickname,json=receiverNickname,proto3" json:"receiver_nickname,omitempty" validate:"required"` // 领取人nickname
	// @inject_tag: validate:"required,gt=0"
	ReceiveTs int64 `protobuf:"varint,4,opt,name=receive_ts,json=receiveTs,proto3" json:"receive_ts,omitempty" validate:"required,gt=0"` // 领取时间
	// @inject_tag: validate:"required,gt=0"
	ReceiveAmount int64 `protobuf:"varint,5,opt,name=receive_amount,json=receiveAmount,proto3" json:"receive_amount,omitempty" validate:"required,gt=0"` // 领取金额
	// @inject_tag: validate:"required,gt=0"
	SenderUid int64 `protobuf:"varint,6,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty" validate:"required,gt=0"` // 派发红包人UID
	// @inject_tag: validate:"required"
	SenderNickname string `protobuf:"bytes,7,opt,name=sender_nickname,json=senderNickname,proto3" json:"sender_nickname,omitempty" validate:"required"` // 派发人nickname
}

func (x *ReceiveRedEnvelope) Reset() {
	*x = ReceiveRedEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveRedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRedEnvelope) ProtoMessage() {}

func (x *ReceiveRedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRedEnvelope.ProtoReflect.Descriptor instead.
func (*ReceiveRedEnvelope) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{11}
}

func (x *ReceiveRedEnvelope) GetEnvId() int64 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *ReceiveRedEnvelope) GetReceiverUid() int64 {
	if x != nil {
		return x.ReceiverUid
	}
	return 0
}

func (x *ReceiveRedEnvelope) GetReceiverNickname() string {
	if x != nil {
		return x.ReceiverNickname
	}
	return ""
}

func (x *ReceiveRedEnvelope) GetReceiveTs() int64 {
	if x != nil {
		return x.ReceiveTs
	}
	return 0
}

func (x *ReceiveRedEnvelope) GetReceiveAmount() int64 {
	if x != nil {
		return x.ReceiveAmount
	}
	return 0
}

func (x *ReceiveRedEnvelope) GetSenderUid() int64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *ReceiveRedEnvelope) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

type RedEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId        int64                     `protobuf:"varint,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`                                                 // 红包ID
	EnvType      pb_enum.RED_ENVELOPE_TYPE `protobuf:"varint,2,opt,name=env_type,json=envType,proto3,enum=pb_enum.RED_ENVELOPE_TYPE" json:"env_type,omitempty"`            // 红包类型 1-均分红包 2-碰运气红包
	ReceiverType pb_enum.RECEIVER_TYPE     `protobuf:"varint,3,opt,name=receiver_type,json=receiverType,proto3,enum=pb_enum.RECEIVER_TYPE" json:"receiver_type,omitempty"` // 接收者类型 1-私聊对方 2-群聊所有人 3-群聊指定人
	TradeNo      string                    `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`                                            // 交易编号
	SenderUid    int64                     `protobuf:"varint,5,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`                                     // 发红包用户ID
	Total        int32                     `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`                                                              // 红包总金额(分)
	Quantity     int32                     `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`                                                        // 红包数量
	Message      int32                     `protobuf:"varint,8,opt,name=message,proto3" json:"message,omitempty"`                                                          // 祝福语
	ExpiredTs    int64                     `protobuf:"varint,9,opt,name=expired_ts,json=expiredTs,proto3" json:"expired_ts,omitempty"`                                     // 过期时间
}

func (x *RedEnvelope) Reset() {
	*x = RedEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedEnvelope) ProtoMessage() {}

func (x *RedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedEnvelope.ProtoReflect.Descriptor instead.
func (*RedEnvelope) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{12}
}

func (x *RedEnvelope) GetEnvId() int64 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *RedEnvelope) GetEnvType() pb_enum.RED_ENVELOPE_TYPE {
	if x != nil {
		return x.EnvType
	}
	return pb_enum.RED_ENVELOPE_TYPE(0)
}

func (x *RedEnvelope) GetReceiverType() pb_enum.RECEIVER_TYPE {
	if x != nil {
		return x.ReceiverType
	}
	return pb_enum.RECEIVER_TYPE(0)
}

func (x *RedEnvelope) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RedEnvelope) GetSenderUid() int64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *RedEnvelope) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RedEnvelope) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RedEnvelope) GetMessage() int32 {
	if x != nil {
		return x.Message
	}
	return 0
}

func (x *RedEnvelope) GetExpiredTs() int64 {
	if x != nil {
		return x.ExpiredTs
	}
	return 0
}

type Sticker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,min=32,max=50"
	FileKey string `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty" validate:"required,min=32,max=50"`
}

func (x *Sticker) Reset() {
	*x = Sticker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sticker) ProtoMessage() {}

func (x *Sticker) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sticker.ProtoReflect.Descriptor instead.
func (*Sticker) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{13}
}

func (x *Sticker) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

type SendChatMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic    pb_enum.TOPIC     `protobuf:"varint,1,opt,name=topic,proto3,enum=pb_enum.TOPIC" json:"topic,omitempty"`
	SubTopic pb_enum.SUB_TOPIC `protobuf:"varint,2,opt,name=sub_topic,json=subTopic,proto3,enum=pb_enum.SUB_TOPIC" json:"sub_topic,omitempty"`
	Msg      *CliChatMessage   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendChatMessageReq) Reset() {
	*x = SendChatMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendChatMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageReq) ProtoMessage() {}

func (x *SendChatMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageReq.ProtoReflect.Descriptor instead.
func (*SendChatMessageReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{14}
}

func (x *SendChatMessageReq) GetTopic() pb_enum.TOPIC {
	if x != nil {
		return x.Topic
	}
	return pb_enum.TOPIC(0)
}

func (x *SendChatMessageReq) GetSubTopic() pb_enum.SUB_TOPIC {
	if x != nil {
		return x.SubTopic
	}
	return pb_enum.SUB_TOPIC(0)
}

func (x *SendChatMessageReq) GetMsg() *CliChatMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

type SendChatMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendChatMessageResp) Reset() {
	*x = SendChatMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendChatMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResp) ProtoMessage() {}

func (x *SendChatMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResp.ProtoReflect.Descriptor instead.
func (*SendChatMessageResp) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{15}
}

func (x *SendChatMessageResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendChatMessageResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MessageOperationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     pb_enum.TOPIC     `protobuf:"varint,1,opt,name=topic,proto3,enum=pb_enum.TOPIC" json:"topic,omitempty"`
	SubTopic  pb_enum.SUB_TOPIC `protobuf:"varint,2,opt,name=sub_topic,json=subTopic,proto3,enum=pb_enum.SUB_TOPIC" json:"sub_topic,omitempty"`
	Operation *MessageOperation `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
}

func (x *MessageOperationReq) Reset() {
	*x = MessageOperationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOperationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOperationReq) ProtoMessage() {}

func (x *MessageOperationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOperationReq.ProtoReflect.Descriptor instead.
func (*MessageOperationReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{16}
}

func (x *MessageOperationReq) GetTopic() pb_enum.TOPIC {
	if x != nil {
		return x.Topic
	}
	return pb_enum.TOPIC(0)
}

func (x *MessageOperationReq) GetSubTopic() pb_enum.SUB_TOPIC {
	if x != nil {
		return x.SubTopic
	}
	return pb_enum.SUB_TOPIC(0)
}

func (x *MessageOperationReq) GetOperation() *MessageOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type MessageOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId int64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`            // 【无需传】
	Platform pb_enum.PLATFORM_TYPE `protobuf:"varint,2,opt,name=platform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"platform,omitempty"` // 无需传】
	ChatId   int64                 `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SeqId    int64                 `protobuf:"varint,4,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	SrvMsgId int64                 `protobuf:"varint,5,opt,name=srv_msg_id,json=srvMsgId,proto3" json:"srv_msg_id,omitempty"`
	Opn      pb_enum.MSG_OPERATION `protobuf:"varint,6,opt,name=opn,proto3,enum=pb_enum.MSG_OPERATION" json:"opn,omitempty"`
	ChatType pb_enum.CHAT_TYPE     `protobuf:"varint,7,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"` // 会话类型
}

func (x *MessageOperation) Reset() {
	*x = MessageOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOperation) ProtoMessage() {}

func (x *MessageOperation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOperation.ProtoReflect.Descriptor instead.
func (*MessageOperation) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{17}
}

func (x *MessageOperation) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageOperation) GetPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.Platform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

func (x *MessageOperation) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *MessageOperation) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *MessageOperation) GetSrvMsgId() int64 {
	if x != nil {
		return x.SrvMsgId
	}
	return 0
}

func (x *MessageOperation) GetOpn() pb_enum.MSG_OPERATION {
	if x != nil {
		return x.Opn
	}
	return pb_enum.MSG_OPERATION(0)
}

func (x *MessageOperation) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

type MessageOperationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MessageOperationResp) Reset() {
	*x = MessageOperationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOperationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOperationResp) ProtoMessage() {}

func (x *MessageOperationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOperationResp.ProtoReflect.Descriptor instead.
func (*MessageOperationResp) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{18}
}

func (x *MessageOperationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MessageOperationResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      int64                    `protobuf:"varint,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`                        // 邀请ID
	CreatedTs     int64                    `protobuf:"varint,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`                     // 邀请时间
	InviteeUid    int64                    `protobuf:"varint,3,opt,name=invitee_uid,json=inviteeUid,proto3" json:"invitee_uid,omitempty"`                  // 被邀请人 UID
	ChatType      pb_enum.CHAT_TYPE        `protobuf:"varint,4,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"` // ChatType
	InvitationMsg string                   `protobuf:"bytes,5,opt,name=invitation_msg,json=invitationMsg,proto3" json:"invitation_msg,omitempty"`          // 邀请消息
	InitiatorInfo *pb_invite.InitiatorInfo `protobuf:"bytes,6,opt,name=initiator_info,json=initiatorInfo,proto3" json:"initiator_info,omitempty"`          // 发起人信息
	ChatInfo      *pb_chat.ChatInfo        `protobuf:"bytes,7,opt,name=chat_info,json=chatInfo,proto3" json:"chat_info,omitempty"`                         // 群信息
}

func (x *ChatInvite) Reset() {
	*x = ChatInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInvite) ProtoMessage() {}

func (x *ChatInvite) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInvite.ProtoReflect.Descriptor instead.
func (*ChatInvite) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{19}
}

func (x *ChatInvite) GetInviteId() int64 {
	if x != nil {
		return x.InviteId
	}
	return 0
}

func (x *ChatInvite) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *ChatInvite) GetInviteeUid() int64 {
	if x != nil {
		return x.InviteeUid
	}
	return 0
}

func (x *ChatInvite) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *ChatInvite) GetInvitationMsg() string {
	if x != nil {
		return x.InvitationMsg
	}
	return ""
}

func (x *ChatInvite) GetInitiatorInfo() *pb_invite.InitiatorInfo {
	if x != nil {
		return x.InitiatorInfo
	}
	return nil
}

func (x *ChatInvite) GetChatInfo() *pb_chat.ChatInfo {
	if x != nil {
		return x.ChatInfo
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId       int64             `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType     pb_enum.CHAT_TYPE `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"`
	Uid          int64             `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Alias        string            `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	MemberAvatar string            `protobuf:"bytes,5,opt,name=member_avatar,json=memberAvatar,proto3" json:"member_avatar,omitempty"`
	RoleId       int32             `protobuf:"varint,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{20}
}

func (x *Contact) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Contact) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *Contact) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Contact) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Contact) GetMemberAvatar() string {
	if x != nil {
		return x.MemberAvatar
	}
	return ""
}

func (x *Contact) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type JoinedGroupChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inviter *pb_chat_member.ChatMemberBasicInfo `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"` // 邀请人
	Invitee *pb_chat_member.ChatMemberBasicInfo `protobuf:"bytes,2,opt,name=invitee,proto3" json:"invitee,omitempty"` // 被邀请人
}

func (x *JoinedGroupChatMessage) Reset() {
	*x = JoinedGroupChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinedGroupChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedGroupChatMessage) ProtoMessage() {}

func (x *JoinedGroupChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedGroupChatMessage.ProtoReflect.Descriptor instead.
func (*JoinedGroupChatMessage) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{21}
}

func (x *JoinedGroupChatMessage) GetInviter() *pb_chat_member.ChatMemberBasicInfo {
	if x != nil {
		return x.Inviter
	}
	return nil
}

func (x *JoinedGroupChatMessage) GetInvitee() *pb_chat_member.ChatMemberBasicInfo {
	if x != nil {
		return x.Invitee
	}
	return nil
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`           // 用户ID
	Platform int32  `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"` // 平台
	Token    string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`        // token
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_proto_rawDescGZIP(), []int{22}
}

func (x *Register) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Register) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pb_msg_msg_proto protoreflect.FileDescriptor

var file_pb_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x1a, 0x12, 0x70, 0x62, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16,
	0x70, 0x62, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x70, 0x62, 0x5f, 0x63,
	0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a,
	0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d,
	0x2e, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x2f, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x53, 0x55, 0x42, 0x5f, 0x54,
	0x4f, 0x50, 0x49, 0x43, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x30,
	0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x73, 0x72,
	0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x53, 0x72, 0x76, 0x22, 0x80,
	0x02, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0f,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0e, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x07, 0x6d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x74, 0x54,
	0x73, 0x22, 0xa4, 0x04, 0x0a, 0x0e, 0x53, 0x72, 0x76, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x72, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x72, 0x76, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a,
	0x0f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d,
	0x2e, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0e,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x46,
	0x72, 0x6f, 0x6d, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x74, 0x54, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x76, 0x5f, 0x74, 0x73,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x72, 0x76, 0x54, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x76, 0x5f, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x72, 0x76, 0x54, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x73, 0x67,
	0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x24, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x3e, 0x0a,
	0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x78, 0x0a,
	0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe6, 0x02, 0x0a, 0x0f, 0x47, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x76,
	0x49, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x52,
	0x45, 0x44, 0x5f, 0x45, 0x4e, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x07, 0x65, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x52, 0x45, 0x43, 0x45, 0x49,
	0x56, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e,
	0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x73,
	0x22, 0x89, 0x02, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x64, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x76, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x55, 0x69,
	0x64, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x55, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xbd, 0x02, 0x0a,
	0x0b, 0x52, 0x65, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x65, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e,
	0x76, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x52, 0x45, 0x44, 0x5f, 0x45, 0x4e, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x52, 0x45, 0x43, 0x45,
	0x49, 0x56, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x4e, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x73, 0x22, 0x24, 0x0a, 0x07,
	0x53, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x4b,
	0x65, 0x79, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x2f, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x53, 0x55, 0x42,
	0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x28, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3b, 0x0a, 0x13, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xa4, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x24, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x08, 0x73, 0x75,
	0x62, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x36, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x6d,
	0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8c,
	0x02, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x4c, 0x41,
	0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x65, 0x71, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x72, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x72, 0x76, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x03, 0x6f, 0x70, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x4f, 0x50,
	0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x03, 0x6f, 0x70, 0x6e, 0x12, 0x2f, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3c, 0x0a,
	0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xb2, 0x02, 0x0a, 0x0a,
	0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x65, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x65, 0x55, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08,
	0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12,
	0x3f, 0x0a, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2e, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0xb9, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x63, 0x68,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x96, 0x01, 0x0a,
	0x16, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x65, 0x22, 0x4e, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xa4, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a,
	0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1e, 0x5a, 0x1c,
	0x6c, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x5f, 0x6d, 0x73, 0x67, 0x3b, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_msg_proto_rawDescOnce sync.Once
	file_pb_msg_msg_proto_rawDescData = file_pb_msg_msg_proto_rawDesc
)

func file_pb_msg_msg_proto_rawDescGZIP() []byte {
	file_pb_msg_msg_proto_rawDescOnce.Do(func() {
		file_pb_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_msg_proto_rawDescData)
	})
	return file_pb_msg_msg_proto_rawDescData
}

var file_pb_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pb_msg_msg_proto_goTypes = []interface{}{
	(*Packet)(nil),                             // 0: pb_msg.Packet
	(*MessageResp)(nil),                        // 1: pb_msg.MessageResp
	(*CliChatMessage)(nil),                     // 2: pb_msg.CliChatMessage
	(*SrvChatMessage)(nil),                     // 3: pb_msg.SrvChatMessage
	(*ReadReceipt)(nil),                        // 4: pb_msg.ReadReceipt
	(*ChatSeq)(nil),                            // 5: pb_msg.ChatSeq
	(*Image)(nil),                              // 6: pb_msg.Image
	(*File)(nil),                               // 7: pb_msg.File
	(*Audio)(nil),                              // 8: pb_msg.Audio
	(*Media)(nil),                              // 9: pb_msg.Media
	(*GiveRedEnvelope)(nil),                    // 10: pb_msg.GiveRedEnvelope
	(*ReceiveRedEnvelope)(nil),                 // 11: pb_msg.ReceiveRedEnvelope
	(*RedEnvelope)(nil),                        // 12: pb_msg.RedEnvelope
	(*Sticker)(nil),                            // 13: pb_msg.Sticker
	(*SendChatMessageReq)(nil),                 // 14: pb_msg.SendChatMessageReq
	(*SendChatMessageResp)(nil),                // 15: pb_msg.SendChatMessageResp
	(*MessageOperationReq)(nil),                // 16: pb_msg.MessageOperationReq
	(*MessageOperation)(nil),                   // 17: pb_msg.MessageOperation
	(*MessageOperationResp)(nil),               // 18: pb_msg.MessageOperationResp
	(*ChatInvite)(nil),                         // 19: pb_msg.ChatInvite
	(*Contact)(nil),                            // 20: pb_msg.Contact
	(*JoinedGroupChatMessage)(nil),             // 21: pb_msg.JoinedGroupChatMessage
	(*Register)(nil),                           // 22: pb_msg.Register
	(pb_enum.TOPIC)(0),                         // 23: pb_enum.TOPIC
	(pb_enum.SUB_TOPIC)(0),                     // 24: pb_enum.SUB_TOPIC
	(pb_enum.MESSAGE_TYPE)(0),                  // 25: pb_enum.MESSAGE_TYPE
	(pb_enum.PLATFORM_TYPE)(0),                 // 26: pb_enum.PLATFORM_TYPE
	(pb_enum.MSG_TYPE)(0),                      // 27: pb_enum.MSG_TYPE
	(pb_enum.CHAT_TYPE)(0),                     // 28: pb_enum.CHAT_TYPE
	(pb_enum.MSG_FROM)(0),                      // 29: pb_enum.MSG_FROM
	(pb_enum.RED_ENVELOPE_TYPE)(0),             // 30: pb_enum.RED_ENVELOPE_TYPE
	(pb_enum.RECEIVER_TYPE)(0),                 // 31: pb_enum.RECEIVER_TYPE
	(pb_enum.MSG_OPERATION)(0),                 // 32: pb_enum.MSG_OPERATION
	(*pb_invite.InitiatorInfo)(nil),            // 33: pb_invite.InitiatorInfo
	(*pb_chat.ChatInfo)(nil),                   // 34: pb_chat.ChatInfo
	(*pb_chat_member.ChatMemberBasicInfo)(nil), // 35: pb_chat_member.ChatMemberBasicInfo
}
var file_pb_msg_msg_proto_depIdxs = []int32{
	23, // 0: pb_msg.Packet.topic:type_name -> pb_enum.TOPIC
	24, // 1: pb_msg.Packet.sub_topic:type_name -> pb_enum.SUB_TOPIC
	25, // 2: pb_msg.Packet.msg_type:type_name -> pb_enum.MESSAGE_TYPE
	26, // 3: pb_msg.CliChatMessage.sender_platform:type_name -> pb_enum.PLATFORM_TYPE
	27, // 4: pb_msg.CliChatMessage.msg_type:type_name -> pb_enum.MSG_TYPE
	26, // 5: pb_msg.SrvChatMessage.sender_platform:type_name -> pb_enum.PLATFORM_TYPE
	28, // 6: pb_msg.SrvChatMessage.chat_type:type_name -> pb_enum.CHAT_TYPE
	29, // 7: pb_msg.SrvChatMessage.msg_from:type_name -> pb_enum.MSG_FROM
	27, // 8: pb_msg.SrvChatMessage.msg_type:type_name -> pb_enum.MSG_TYPE
	29, // 9: pb_msg.ChatSeq.msg_from:type_name -> pb_enum.MSG_FROM
	30, // 10: pb_msg.GiveRedEnvelope.env_type:type_name -> pb_enum.RED_ENVELOPE_TYPE
	31, // 11: pb_msg.GiveRedEnvelope.receiver_type:type_name -> pb_enum.RECEIVER_TYPE
	30, // 12: pb_msg.RedEnvelope.env_type:type_name -> pb_enum.RED_ENVELOPE_TYPE
	31, // 13: pb_msg.RedEnvelope.receiver_type:type_name -> pb_enum.RECEIVER_TYPE
	23, // 14: pb_msg.SendChatMessageReq.topic:type_name -> pb_enum.TOPIC
	24, // 15: pb_msg.SendChatMessageReq.sub_topic:type_name -> pb_enum.SUB_TOPIC
	2,  // 16: pb_msg.SendChatMessageReq.msg:type_name -> pb_msg.CliChatMessage
	23, // 17: pb_msg.MessageOperationReq.topic:type_name -> pb_enum.TOPIC
	24, // 18: pb_msg.MessageOperationReq.sub_topic:type_name -> pb_enum.SUB_TOPIC
	17, // 19: pb_msg.MessageOperationReq.operation:type_name -> pb_msg.MessageOperation
	26, // 20: pb_msg.MessageOperation.platform:type_name -> pb_enum.PLATFORM_TYPE
	32, // 21: pb_msg.MessageOperation.opn:type_name -> pb_enum.MSG_OPERATION
	28, // 22: pb_msg.MessageOperation.chat_type:type_name -> pb_enum.CHAT_TYPE
	28, // 23: pb_msg.ChatInvite.chat_type:type_name -> pb_enum.CHAT_TYPE
	33, // 24: pb_msg.ChatInvite.initiator_info:type_name -> pb_invite.InitiatorInfo
	34, // 25: pb_msg.ChatInvite.chat_info:type_name -> pb_chat.ChatInfo
	28, // 26: pb_msg.Contact.chat_type:type_name -> pb_enum.CHAT_TYPE
	35, // 27: pb_msg.JoinedGroupChatMessage.inviter:type_name -> pb_chat_member.ChatMemberBasicInfo
	35, // 28: pb_msg.JoinedGroupChatMessage.invitee:type_name -> pb_chat_member.ChatMemberBasicInfo
	14, // 29: pb_msg.Message.SendChatMessage:input_type -> pb_msg.SendChatMessageReq
	16, // 30: pb_msg.Message.MessageOperation:input_type -> pb_msg.MessageOperationReq
	15, // 31: pb_msg.Message.SendChatMessage:output_type -> pb_msg.SendChatMessageResp
	18, // 32: pb_msg.Message.MessageOperation:output_type -> pb_msg.MessageOperationResp
	31, // [31:33] is the sub-list for method output_type
	29, // [29:31] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_pb_msg_msg_proto_init() }
func file_pb_msg_msg_proto_init() {
	if File_pb_msg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CliChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrvChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Audio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveRedEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveRedEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sticker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendChatMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendChatMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOperationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOperationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinedGroupChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_msg_msg_proto_goTypes,
		DependencyIndexes: file_pb_msg_msg_proto_depIdxs,
		MessageInfos:      file_pb_msg_msg_proto_msgTypes,
	}.Build()
	File_pb_msg_msg_proto = out.File
	file_pb_msg_msg_proto_rawDesc = nil
	file_pb_msg_msg_proto_goTypes = nil
	file_pb_msg_msg_proto_depIdxs = nil
}
