// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: pb_chat_msg/chat_msg.proto

package pb_chat_msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChatMessage_GetChatMessages_FullMethodName    = "/pb_chat_msg.ChatMessage/GetChatMessages"
	ChatMessage_GetChatMessageList_FullMethodName = "/pb_chat_msg.ChatMessage/GetChatMessageList"
	ChatMessage_SearchMessage_FullMethodName      = "/pb_chat_msg.ChatMessage/SearchMessage"
	ChatMessage_MessageOperation_FullMethodName   = "/pb_chat_msg.ChatMessage/MessageOperation"
)

// ChatMessageClient is the client API for ChatMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatMessageClient interface {
	GetChatMessages(ctx context.Context, in *GetChatMessagesReq, opts ...grpc.CallOption) (*GetChatMessagesResp, error)
	GetChatMessageList(ctx context.Context, in *GetChatMessageListReq, opts ...grpc.CallOption) (*GetChatMessageListResp, error)
	SearchMessage(ctx context.Context, in *SearchMessageReq, opts ...grpc.CallOption) (*SearchMessageResp, error)
	MessageOperation(ctx context.Context, in *MessageOperationReq, opts ...grpc.CallOption) (*MessageOperationResp, error)
}

type chatMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewChatMessageClient(cc grpc.ClientConnInterface) ChatMessageClient {
	return &chatMessageClient{cc}
}

func (c *chatMessageClient) GetChatMessages(ctx context.Context, in *GetChatMessagesReq, opts ...grpc.CallOption) (*GetChatMessagesResp, error) {
	out := new(GetChatMessagesResp)
	err := c.cc.Invoke(ctx, ChatMessage_GetChatMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageClient) GetChatMessageList(ctx context.Context, in *GetChatMessageListReq, opts ...grpc.CallOption) (*GetChatMessageListResp, error) {
	out := new(GetChatMessageListResp)
	err := c.cc.Invoke(ctx, ChatMessage_GetChatMessageList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageClient) SearchMessage(ctx context.Context, in *SearchMessageReq, opts ...grpc.CallOption) (*SearchMessageResp, error) {
	out := new(SearchMessageResp)
	err := c.cc.Invoke(ctx, ChatMessage_SearchMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageClient) MessageOperation(ctx context.Context, in *MessageOperationReq, opts ...grpc.CallOption) (*MessageOperationResp, error) {
	out := new(MessageOperationResp)
	err := c.cc.Invoke(ctx, ChatMessage_MessageOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatMessageServer is the server API for ChatMessage service.
// All implementations must embed UnimplementedChatMessageServer
// for forward compatibility
type ChatMessageServer interface {
	GetChatMessages(context.Context, *GetChatMessagesReq) (*GetChatMessagesResp, error)
	GetChatMessageList(context.Context, *GetChatMessageListReq) (*GetChatMessageListResp, error)
	SearchMessage(context.Context, *SearchMessageReq) (*SearchMessageResp, error)
	MessageOperation(context.Context, *MessageOperationReq) (*MessageOperationResp, error)
	mustEmbedUnimplementedChatMessageServer()
}

// UnimplementedChatMessageServer must be embedded to have forward compatible implementations.
type UnimplementedChatMessageServer struct {
}

func (UnimplementedChatMessageServer) GetChatMessages(context.Context, *GetChatMessagesReq) (*GetChatMessagesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatMessages not implemented")
}
func (UnimplementedChatMessageServer) GetChatMessageList(context.Context, *GetChatMessageListReq) (*GetChatMessageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatMessageList not implemented")
}
func (UnimplementedChatMessageServer) SearchMessage(context.Context, *SearchMessageReq) (*SearchMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMessage not implemented")
}
func (UnimplementedChatMessageServer) MessageOperation(context.Context, *MessageOperationReq) (*MessageOperationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageOperation not implemented")
}
func (UnimplementedChatMessageServer) mustEmbedUnimplementedChatMessageServer() {}

// UnsafeChatMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatMessageServer will
// result in compilation errors.
type UnsafeChatMessageServer interface {
	mustEmbedUnimplementedChatMessageServer()
}

func RegisterChatMessageServer(s grpc.ServiceRegistrar, srv ChatMessageServer) {
	s.RegisterService(&ChatMessage_ServiceDesc, srv)
}

func _ChatMessage_GetChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServer).GetChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessage_GetChatMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServer).GetChatMessages(ctx, req.(*GetChatMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessage_GetChatMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatMessageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServer).GetChatMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessage_GetChatMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServer).GetChatMessageList(ctx, req.(*GetChatMessageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessage_SearchMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServer).SearchMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessage_SearchMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServer).SearchMessage(ctx, req.(*SearchMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessage_MessageOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageOperationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServer).MessageOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessage_MessageOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServer).MessageOperation(ctx, req.(*MessageOperationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatMessage_ServiceDesc is the grpc.ServiceDesc for ChatMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_chat_msg.ChatMessage",
	HandlerType: (*ChatMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatMessages",
			Handler:    _ChatMessage_GetChatMessages_Handler,
		},
		{
			MethodName: "GetChatMessageList",
			Handler:    _ChatMessage_GetChatMessageList_Handler,
		},
		{
			MethodName: "SearchMessage",
			Handler:    _ChatMessage_SearchMessage_Handler,
		},
		{
			MethodName: "MessageOperation",
			Handler:    _ChatMessage_MessageOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_chat_msg/chat_msg.proto",
}
