---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by saeipi.
--- DateTime: 2022/11/24 12:12
---

for i=1,  #KEYS do
    redis.call('SET', KEYS[i], ARGV[i+1], "EX", ARGV[1])
end
return 0