---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by saeipi.
--- DateTime: 2022/12/3 19:15
---

local KEYS = {"LARK:CONVO:LIST:","3600","LARK:CONVO:SEQ_ID:","9","60"}
local ARGV = {1,2,3,4}

local prefix1 = KEYS[1]
local chatId = KEYS[2]

local prefix2 = KEYS[3]
local seqId = KEYS[4]

local timestamp = tonumber(KEYS[5])
local key = ""
local uid = 0
for i=1, #ARGV do
    uid = ARGV[i]
    key = string.format("%s%d",prefix1,uid)
    print('ZADD', key, timestamp, chatId)
    key = string.format("%s%d",prefix2,uid)
    print('hmset', key, chatId, seqId)
end
return 0

--redis-cli -h 127.0.0.1 -p 63791 -a lark2022 script load "
--local prefix = KEYS[1]
--local chatId = KEYS[2]
--local timestamp = tonumber(KEYS[3])
--local key = \"\"
--for i=1, #ARGV do
--    key = string.format(\"%s%d\",prefix,ARGV[i])
--    redis.call('ZADD', key, timestamp, chatId)
--end
--return 0
--"