package constant

const (
	PAYPAL_PAYMENT_AUTHORIZATION_CREATED = "PAYMENT.AUTHORIZATION.CREATED" // 付款授权创建
	PAYPAL_PAYMENT_AUTHORIZATION_VOIDED  = "PAYMENT.AUTHORIZATION.VOIDED"  // 由于授权达到 30 天有效期或使用作废授权支付 API 手动作废授权，支付授权将被作废。
	PAYPAL_PAYMENT_CAPTURE_DECLINED      = "PAYMENT.CAPTURE.DECLINED"      // 付款捕获被拒绝
	PAYPAL_PAYMENT_CAPTURE_COMPLETED     = "PAYMENT.CAPTURE.COMPLETED"     // 付款捕获完成
	PAYPAL_PAYMENT_CAPTURE_PENDING       = "PAYMENT.CAPTURE.PENDING"       // 付款捕获的状态更改为待处理。
	PAYPAL_PAYMENT_CAPTURE_REFUNDED      = "PAYMENT.CAPTURE.REFUNDED"      // 商家对付款捕获进行退款。
	PAYPAL_PAYMENT_CAPTURE_REVERSED      = "PAYMENT.CAPTURE.REVERSED"      // PayPal 撤销付款捕获
	PAYPAL_PAYMENT_SALE_COMPLETED        = "PAYMENT.SALE.COMPLETED"        // 支付已完成,销售已成交
	PAYPAL_PAYMENT_SALE_REVERSED         = "PAYMENT.SALE.REVERSED"         // 销售被取消/退款,支付被撤销
	PAYPAL_PAYMENT_SALE_PENDING          = "PAYMENT.SALE.PENDING"          // 支付正在等待处理中,销售仍在待定状态
	PAYPAL_PAYMENT_SALE_DENIED           = "PAYMENT.SALE.DENIED"           // 支付被拒绝,销售未成功
	PAYPAL_PAYMENT_SALE_REFUNDED         = "PAYMENT.SALE.REFUNDED"         // 退款:销售已被退款,支付已退回
)

const (
	PAYPAL_STATUS_COMPLETED = "completed"
)

const (
	PAYPAL_MERCHANT_ID = "JHBQ8Q2ZCX998"
)
