package service

const (
	ERROR_CODE_CHAT_MSG_REDIS_GET_FAILED     int32 = 900001
	ERROR_CODE_CHAT_MSG_ENCODING_FAILED      int32 = 900002
	ERROR_CODE_CHAT_MSG_SEARCH_FAILED        int32 = 900003
	ERROR_CODE_CHAT_MSG_DECODE_FAILED        int32 = 900004
	ERROR_CODE_CHAT_MSG_NON_CHAT_MEMBER      int32 = 900005
	ERROR_CODE_CHAT_MSG_QUERY_DB_FAILED      int32 = 900006
	ERROR_CODE_CHAT_MSG_UPDATE_CHCHE_FAILED  int32 = 900007
	ERROR_CODE_CHAT_MSG_UPDATE_VALUE_FAILED  int32 = 900008
	ERROR_CODE_CHAT_MSG_BEYOND_OPERABLE_TIME int32 = 900009
	ERROR_CODE_CHAT_MSG_ENQUEUE_FAILED       int32 = 900010
	ERROR_CODE_CHAT_MSG_GRPC_SERVICE_FAILURE int32 = 900011
)

const (
	ERROR_CHAT_MSG_REDIS_GET_FAILED     = "读取 redis 缓存失败"
	ERROR_CHAT_MSG_ENCODING_FAILED      = "编码失败"
	ERROR_CHAT_MSG_SEARCH_FAILED        = "搜索失败"
	ERROR_CHAT_MSG_DECODE_FAILED        = "解码失败"
	ERROR_CHAT_MSG_NON_CHAT_MEMBER      = "非 Chat 成员"
	ERROR_CHAT_MSG_QUERY_DB_FAILED      = "查询失败"
	ERROR_CHAT_MSG_UPDATE_CHCHE_FAILED  = "更新缓存消息失败"
	ERROR_CHAT_MSG_UPDATE_VALUE_FAILED  = "更新Value失败"
	ERROR_CHAT_MSG_BEYOND_OPERABLE_TIME = "仅可撤回 10 minutes 内的消息"
	ERROR_CHAT_MSG_ENQUEUE_FAILED       = "消息入队失败"
	ERROR_CHAT_MSG_GRPC_SERVICE_FAILURE = "服务故障"
)
