package service

import "errors"

const (
	ERROR_CODE_CHAT_INVITE_PROTOCOL_UNMARSHAL_ERR   int32 = 10001
	ERROR_CODE_CHAT_INVITE_GRPC_SERVICE_FAILURE     int32 = 10002
	ERROR_CODE_CHAT_INVITE_INSERT_VALUE_FAILED      int32 = 10003
	ERROR_CODE_CHAT_INVITE_UPDATE_VALUE_FAILED      int32 = 10004
	ERROR_CODE_CHAT_INVITE_QUERY_DB_FAILED          int32 = 10005
	ERROR_CODE_CHAT_INVITE_INITIATOR_INVITEE_SAME   int32 = 10006
	ERROR_CODE_CHAT_INVITE_HAS_JOINED_CHAT          int32 = 10007
	ERROR_CODE_CHAT_INVITE_PARAM_ERR                int32 = 10008
	ERROR_CODE_CHAT_INVITE_HAS_HANDLED              int32 = 10009
	ERROR_CODE_CHAT_INVITE_BAD_HANDLER              int32 = 10010
	ERROR_CODE_CHAT_INVITE_CACHE_CHAT_MEMBER_FAILED int32 = 10011
	ERROR_CODE_CHAT_INVITE_PARAMETER_ERROR          int32 = 10012
	ERROR_CODE_CHAT_INVITE_ENQUEUE_FAILED           int32 = 10013
	ERROR_CODE_CHAT_INVITE_INCR_SEQ_ID_FAILED       int32 = 10014
	ERROR_CODE_CHAT_INVITE_DECR_SEQ_ID_FAILED       int32 = 10015
	ERROR_CODE_CHAT_INVITE_PROCESSED                int32 = 10016
	ERROR_CODE_CHAT_INVITE_ALREADY_MEMBER           int32 = 10017
	ERROR_CODE_CHAT_INVITE_REDIS_GET_FAILED         int32 = 10018
	ERROR_CODE_CHAT_INVITE_PROTOCOL_MARSHAL_ERR     int32 = 10019
	ERROR_CODE_CHAT_INVITE_REPEAT_INVITATION        int32 = 10020
)

const (
	ERROR_CHAT_INVITE_PROTOCOL_UNMARSHAL_ERR   = "协议反序列化错误"
	ERROR_CHAT_INVITE_GRPC_SERVICE_FAILURE     = "服务故障"
	ERROR_CHAT_INVITE_INSERT_VALUE_FAILED      = "数据入库失败"
	ERROR_CHAT_INVITE_UPDATE_VALUE_FAILED      = "更新Value失败"
	ERROR_CHAT_INVITE_QUERY_DB_FAILED          = "查询失败"
	ERROR_CHAT_INVITE_INITIATOR_INVITEE_SAME   = "发起者和被邀请人为同一人"
	ERROR_CHAT_INVITE_HAS_JOINED_CHAT          = "已经加入了"
	ERROR_CHAT_INVITE_PARAM_ERR                = "参数错误"
	ERROR_CHAT_INVITE_HAS_HANDLED              = "邀请已处理"
	ERROR_CHAT_INVITE_BAD_HANDLER              = "不合法的处理人"
	ERROR_CHAT_INVITE_CACHE_CHAT_MEMBER_FAILED = "缓存Chat Member失败"
	ERROR_CHAT_INVITE_PARAMETER_ERROR          = "参数错误"
	ERROR_CHAT_INVITE_ENQUEUE_FAILED           = "消息入队失败"
	ERROR_CHAT_INVITE_INCR_SEQ_ID_FAILED       = "生成 Sequence ID 失败"
	ERROR_CHAT_INVITE_DECR_SEQ_ID_FAILED       = "更新 Sequence ID 失败"
	ERROR_CHAT_INVITE_PROCESSED                = "邀请已处理"
	ERROR_CHAT_INVITE_ALREADY_MEMBER           = "已经是Chat成员"
	ERROR_CHAT_INVITE_REDIS_GET_FAILED         = "读取redis缓存失败"
	ERROR_CHAT_INVITE_PROTOCOL_MARSHAL_ERR     = "协议序列化错误"
	ERROR_CHAT_INVITE_REPEAT_INVITATION        = "存在重复邀请"
)

var (
	CONST_CHAT_INVITE_JOINED_CHAT_GROUP_CONJUNCTION = "加入群聊"
)

var (
	ERR_CHAT_INVITE_QUERY_DB_FAILED  = errors.New("查询失败")
	ERR_CHAT_INVITE_REPEAT_OPERATION = errors.New("重复的操作")
)
