package gateway

const (
	ERROR_CODE_GATEWAY_MSG_UNMARSHAL_ERR         int32 = 3201
	ERROR_CODE_GATEWAY_MSG_MARSHAL_ERR           int32 = 3202
	ERROR_CODE_GATEWAY_MSG_ASSEMBLY_PROTOCOL_ERR int32 = 3203
)

const (
	ERROR_GATEWAY_MSG_UNMARSHAL_ERR         = "协议反序列化错误"
	ERROR_GATEWAY_MSG_MARSHAL_ERR           = "协议序列化错误"
	ERROR_GATEWAY_MSG_ASSEMBLY_PROTOCOL_ERR = "组装协议错误"
)
