package service

const (
	ERROR_CODE_MSG_HOT_PROTOCOL_UNMARSHAL_FAILED int32 = 6001
	ERROR_CODE_MSG_HOT_GRPC_SERVICE_FAILURE      int32 = 6002
	ERROR_CODE_MSG_HOT_MSG_PUSH_FAILED           int32 = 6003
	ERROR_CODE_MSG_HOT_MSG_ENQUEUE_FAILED        int32 = 6004
	ERROR_CODE_MSG_HOT_GET_SEQ_ID_FAILED         int32 = 6005
	ERROR_CODE_MSG_HOT_INSERT_MESSAGE_FAILED     int32 = 6006
	ERROR_CODE_MSG_HOT_CHCHE_MESSAGE_FAILED      int32 = 6007
)

const (
	ERROR_MSG_HOT_PROTOCOL_UNMARSHAL_FAILED = "协议反序列化错误"
	ERROR_MSG_HOT_GRPC_SERVICE_FAILURE      = "服务故障"
	ERROR_MSG_HOT_MSG_PUSH_FAILED           = "消息推送失败"
	ERROR_MSG_HOT_MSG_ENQUEUE_FAILED        = "消息ENQUEUE失败"
	ERROR_MSG_HOT_GET_SEQ_ID_FAILED         = "生成 SEQUENCE ID 失败"
	ERROR_MSG_HOT_INSERT_MESSAGE_FAILED     = "消息入库失败"
	ERROR_MSG_HOT_CHCHE_MESSAGE_FAILED      = "消息缓存失败"
)
