package xhttp

const (
	ERROR_CODE_HTTP_JWT_TOKEN_ERR     int32 = 401 // TOKEN 错误
	ERROR_CODE_HTTP_TOO_MANY_REQUESTS       = 429
)

const (
	ERROR_CODE_HTTP_USER_ID_DOESNOT_EXIST    int32 = 601 // 用户ID信息缺失
	ERROR_CODE_HTTP_PLATFORM_DOESNOT_EXIST   int32 = 602 // 平台信息缺失
	ERROR_CODE_HTTP_SESSION_ID_DOESNOT_EXIST int32 = 603 // SESSION ID 缺失
	ERROR_CODE_HTTP_READ_SESSION_ID_FAILED   int32 = 604 // 读取会话ID失败
	ERROR_CODE_HTTP_TOKEN_EXPIRES            int32 = 605 // Token 过期
	ERROR_CODE_HTTP_ACCOUNT_KICKED_OUT       int32 = 606 // 账号被踢出
	ERROR_CODE_HTTP_GITHUB_TOKEN_EXPIRES     int32 = 607 // Token 过期
)

const (
	ERROR_CODE_HTTP_REQ_DESERIALIZE_FAILED           int32 = 701 // 请求参数序列化错误
	ERROR_CODE_HTTP_REQ_PARAM_ERR                    int32 = 702 // 请求参数错误
	ERROR_CODE_HTTP_REQ_NOT_AUTHORIZED               int32 = 703 // 没有授权
	ERROR_CODE_HTTP_REGISTER_FAILED                  int32 = 704 // 注册失败
	ERROR_CODE_HTTP_TOKEN_FAILED                     int32 = 705 // 获取TOKEN失败
	ERROR_CODE_HTTP_JWT_TOKEN_UUID_DOESNOT_EXIST     int32 = 706 // Token 信息缺失
	ERROR_CODE_HTTP_GET_USER_INFO_FAILED             int32 = 707 // 获取用户信息失败
	ERROR_CODE_HTTP_ADD_FRIEND_FAILED                int32 = 708 // 添加好友失败
	ERROR_CODE_HTTP_SERVICE_FAILURE                  int32 = 709 // 服务故障
	ERROR_CODE_HTTP_MESSAGE_ENQUEUE_FAILED           int32 = 710 // 消息入队失败
	ERROR_CODE_HTTP_PRESIGNED_FAILED                 int32 = 711 // 上传文件预先签署失败
	ERROR_CODE_HTTP_READ_UPLOAD_FILE_FAILED          int32 = 712 // 读取上传文件失败
	ERROR_CODE_HTTP_OPEN_UPLOAD_FILE_FAILED          int32 = 713 // 打开上传文件失败
	ERROR_CODE_HTTP_CROP_PHOTO_FAILED                int32 = 714 // 裁剪图片失败
	ERROR_CODE_HTTP_PAGINATION_LIMIT_EXCEEDED        int32 = 715 // 超出分页限制
	ERROR_CODE_HTTP_ALIPAY_NOTIFY_VERIFY_SIGN_FAILED int32 = 716 // alipay通知验签失败
)
const (
	ERROR_CODE_HTTP_400          = 400
	ERROR_CODE_HTTP_UNAUTHORIZED = 401
)
