package xhttp

const (
	ERROR_HTTP_JWT_TOKEN_ERR                    = "无效的会话令牌"
	ERROR_HTTP_USER_ID_DOESNOT_EXIST            = "缺少用户ID信息"
	ERROR_HTTP_PLATFORM_DOESNOT_EXIST           = "缺少平台信息"
	ERROR_HTTP_SESSION_ID_DOESNOT_EXIST         = "会话ID缺失"
	ERROR_HTTP_READ_SESSION_ID_FAILED           = "读取会话ID失败"
	ERROR_HTTP_TOKEN_EXPIRES                    = "Token 已过期"
	ERROR_HTTP_GITHUB_TOKEN_EXPIRES             = "Github Token 已过期，请重新登录"
	ERROR_HTTP_ACCOUNT_KICKED_OUT               = "您的账号已在其他地方登录，请重新登录"
	ERROR_HTTP_REQ_DESERIALIZE_FAILED           = "请求参数反序列化失败"
	ERROR_HTTP_REQ_PARAM_ERR                    = "请求参数不正确"
	ERROR_HTTP_JWT_TOKEN_UUID_DOESNOT_EXIST     = "Token 身份标识信息缺失"
	ERROR_HTTP_TOKEN_AUTHENTICATION_FAILED      = "Token 验证失败"
	ERROR_HTTP_GET_USER_INFO_FAILED             = "获取用户信息失败"
	ERROR_HTTP_SERVICE_FAILURE                  = "服务发生故障"
	ERROR_HTTP_MESSAGE_ENQUEUE_FAILED           = "消息入队失败"
	ERROR_HTTP_PRESIGNED_FAILED                 = "上传文件预签名失败"
	ERROR_HTTP_READ_UPLOAD_FILE_FAILED          = "读取上传文件失败"
	ERROR_HTTP_OPEN_UPLOAD_FILE_FAILED          = "打开上传文件失败"
	ERROR_HTTP_CROP_PHOTO_FAILED                = "图片裁剪失败"
	ERROR_HTTP_PAGINATION_LIMIT_EXCEEDED        = "超出分页限制"
	ERROR_HTTP_ALIPAY_NOTIFY_VERIFY_SIGN_FAILED = "Alipay通知验签失败"
	ERROR_HTTP_TOO_MANY_REQUESTS                = "当前IP请求过于频繁，请一分钟后重试"
)
