package service

const (
	ERROR_CODE_WS_PROTOCOL_UNMARSHAL_ERR int32 = 3101
	ERROR_CODE_WS_PROTOCOL_MARSHAL_ERR   int32 = 3102
	ERROR_CODE_WS_TOPIC_ID_ERR           int32 = 3103
	ERROR_CODE_WS_GRPC_SERVICE_FAILURE   int32 = 3104
	ERROR_CODE_WS_ASSEMBLY_PROTOCOL_ERR  int32 = 3105
	ERROR_CODE_WS_SERVER_OVERLOAD        int32 = 3106
)

const (
	ERROR_WS_PROTOCOL_UNMARSHAL_ERR = "协议反序列化错误"
	ERROR_WS_PROTOCOL_MARSHAL_ERR   = "协议列化错误"
	ERROR_WS_TOPIC_ID_ERR           = "消息主题错误"
	ERROR_WS_GRPC_SERVICE_FAILURE   = "服务故障"
	ERROR_WS_ASSEMBLY_PROTOCOL_ERR  = "组装协议错误"
	ERROR_WS_SERVER_OVERLOAD        = "服务器超负荷"
)
